package terminal

const BACKGROUND_BLACK = "\033[40m"
const BACKGROUND_RED = "\033[41m"
const BACKGROUND_GREEN = "\033[42m"
const BACKGROUND_YELLOW = "\033[43m"
const BACKGROUND_BLUE = "\033[44m"
const BACKGROUND_MAGENTA = "\033[45m"
const BACKGROUND_CYAN = "\033[46m"
const BACKGROUND_WHITE = "\033[47m"
const BACKGROUND_DEFAULT = "\033[49m"

const FOREGROUND_BLACK = "\033[30m"
const FOREGROUND_RED = "\033[31m"
const FOREGROUND_GREEN = "\033[32m"
const FOREGROUND_YELLOW = "\033[33m"
const FOREGROUND_BLUE = "\033[34m"
const FOREGROUND_MAGENTA = "\033[35m"
const FOREGROUND_CYAN = "\033[36m"
const FOREGROUND_WHITE = "\033[37m"
const FOREGROUND_DEFAULT = "\033[39m"

const BLACK_BLOCK = BACKGROUND_BLACK + " " + BACKGROUND_DEFAULT
const RED_BLOCK = BACKGROUND_RED + " " + BACKGROUND_DEFAULT
const GREEN_BLOCK = BACKGROUND_GREEN + " " + BACKGROUND_DEFAULT
const YELLOW_BLOCK = BACKGROUND_YELLOW + " " + BACKGROUND_DEFAULT
const BLUE_BLOCK = BACKGROUND_BLUE + " " + BACKGROUND_DEFAULT
const MAGENTA_BLOCK = BACKGROUND_MAGENTA + " " + BACKGROUND_DEFAULT
const CYAN_BLOCK = BACKGROUND_CYAN + " " + BACKGROUND_DEFAULT
const WHITE_BLOCK = BACKGROUND_WHITE + " " + BACKGROUND_DEFAULT
